source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'dotenv-rails', :groups => [:development, :test]
gem 'jsonapi-resources'
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

gem 'sdoc', '~> 0.4.0', group: :doc
