source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'jsonapi-resources'
gem "rack-cors", require: "rack/cors"

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
 gem 'dotenv-rails'
 gem 'byebug'
end

gem 'sdoc', '~> 0.4.0', group: :doc
