source 'https://rubygems.org'

ruby '2.2.3'

gem 'rails', '4.2.4'
gem 'pg'
gem 'jsonapi-resources'
gem 'rack-cors', require: 'rack/cors'
gem 'rails_api_auth', github: 'simplabs/rails_api_auth', branch: 'master'
gem 'pry'

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
 gem 'dotenv-rails'
 gem 'byebug'
end

gem 'sdoc', '~> 0.4.0', group: :doc
